Kit (!c16K!c00ulina ed!c16IT!c00or) is supposed to be a simple graphical
editor for Linux. It is aimed as an editor which be can be
used with a few trials. However few tips may be useful.

!c381. Markpos
This position is used by operations like ,!c38'write to'!c00, !c38'cut'!c00
and !c38'copy'!c00. It is used as the start position for these commands.
Also the !c38'Go'!c00 button (int the lower bar) can take the cursor
to !c38Markpos!c00. The !c38Markpos!c00 can be set either by pressing the !c38'Mark'!c00
button in the top bar or by typing explicitly at the
!c38'MarkPos'!c00 text box in bottom bar.

!c382. Search and Replace strings.
These strings are set at the respective text boxes in top
bar. Either of the strings can be empty. The search string
is used for searching the pattern. A !c38'Replace'!c00 will
replace the next search string with the replace string.
If the search string is empty, a !c38'Replace'!c00 will insert the
replace string at the current cursor position.
If the replace string is empty , a !c38'Replace'!c00 will remove the
next search string.

!c38Note: Text input box  can be cleared by typing an !c33'Esc'!c38 character.
