int kgeditKEDtablecallback(int cellno,int i,void *Tmp) ;
int kgeditKEDscrollcallback(double val,int i,void *Tmp) ;
int kgeditKEDfinishcallback(int butno,int i,void *Tmp) ;
void  kgeditKEDfinishinit (DIL *B,void *pt) ;
int kgeditKEDopt2callback(int butno,int i,void *Tmp) ;
void  kgeditKEDopt2init (DIN *B,void *pt) ;
int kgeditKEDopt1callback(int butno,int i,void *Tmp) ;
void  kgeditKEDopt1init (DIN *B,void *pt) ;
int kgeditKEDmarkcallback(int cellno,int i,void *Tmp) ;
int kgeditKEDgocallback(int butno,int i,void *Tmp) ;
void  kgeditKEDgoinit (DIN *B,void *pt) ;
int kgeditKEDsavecallback(int butno,int i,void *Tmp) ;
void  kgeditKEDsaveinit (DIN *B,void *pt) ;
int kgeditKEDstringscallback(int butno,int i,void *Tmp) ;
void  kgeditKEDstringsinit (DIN *B,void *pt) ;
int kgeditKEDsearchcallback(int butno,int i,void *Tmp) ;
void  kgeditKEDsearchinit (DIN *B,void *pt) ;
int kgeditKEDreplacecallback(int butno,int i,void *Tmp) ;
void  kgeditKEDreplaceinit (DIN *B,void *pt) ;
int kgeditKEDdircallback(int butno,int i,void *Tmp) ;
void  kgeditKEDdirinit (DIN *B,void *pt) ;
int kgeditKEDhelpcallback(int butno,int i,void *Tmp) ;
void  kgeditKEDhelpinit (DIN *B,void *pt) ;
int kgeditKEDsetupcallback(int butno,int i,void *Tmp) ;
void  kgeditKEDsetupinit (DIN *B,void *pt) ;
int kgeditKEDstboxcallback(int cellno,int i,void *Tmp) ;
int kgeditKEDrtboxcallback(int cellno,int i,void *Tmp) ;
int kgeditinit(void *Tmp) ;
int kgeditcleanup(void *Tmp) ;
void *Runkgedit(void *,void *) ;
int MakekgeditGroup(DIALOG *,void *) ;
void * kgeditAction(void *,void *) ;
int kgeditSetup(void *Tmp,void *args) ;
int Modifykgedit(void *Tmp,int GrpId) ;
int kgeditCallBack(void *Tmp,void *tmp) ;
int kgeditResizeCallBack(void *Tmp) ;
int kgeditWaitCallBack(void *Tmp) ;
