int  ScrollTabletablebox1callback(int cellno,int i,void *Tmp);
int  ScrollTablevertscroll1callback(double val,int i,void *Tmp) ;
int  ScrollTablesplbutton1callback(int butno,int i,void *Tmp) ;
void  ScrollTablesplbutton1init(DIL *B,void *pt) ;
int  ScrollTablebutton1callback(int butno,int i,void *Tmp) ;
void  ScrollTablebutton1init(DIN *B,void *pt) ;
int  ScrollTablebutton2callback(int butno,int i,void *Tmp) ;
void  ScrollTablebutton2init(DIN *B,void *pt) ;
int  ScrollTabletextbox1callback(int cellno,int i,void *Tmp);
int  ScrollTablebutton3callback(int butno,int i,void *Tmp) ;
void  ScrollTablebutton3init(DIN *B,void *pt) ;
int  ScrollTablebutton4callback(int butno,int i,void *Tmp) ;
void  ScrollTablebutton4init(DIN *B,void *pt) ;
int  ScrollTablebutton5callback(int butno,int i,void *Tmp) ;
void  ScrollTablebutton5init(DIN *B,void *pt) ;
int  ScrollTabletextbox2callback(int cellno,int i,void *Tmp);
int  ScrollTabletextbox3callback(int cellno,int i,void *Tmp);
int  ScrollTablebutton6callback(int butno,int i,void *Tmp) ;
void  ScrollTablebutton6init(DIN *B,void *pt) ;
int  ScrollTablebutton7callback(int butno,int i,void *Tmp) ;
void  ScrollTablebutton7init(DIN *B,void *pt) ;
int  ScrollTablebutton8callback(int butno,int i,void *Tmp) ;
void  ScrollTablebutton8init(DIN *B,void *pt) ;
int ScrollTableinit(void *Tmp) ;
int ScrollTablecleanup(void *Tmp) ;
int ModifyScrollTable(void *Tmp,int GrpId) ;
int ScrollTableCallBack(void *Tmp,void *tmp) ;
int ScrollTableResizeCallBack(void *Tmp) ;
int ScrollTableWaitCallBack(void *Tmp) ;
