int  Setupbutton1callback(int butno,int i,void *Tmp) ;
void  Setupbutton1init(DIN *B,void *pt) ;
int  Setuptextbox1callback(int cellno,int i,void *Tmp);
int  Setupbrowser1callback(int item,int i,void *Tmp) ;
int  Setupbutton2callback(int butno,int i,void *Tmp) ;
void  Setupbutton2init(DIN *B,void *pt) ;
int  Setupbutton3callback(int butno,int i,void *Tmp) ;
void  Setupbutton3init(DIN *B,void *pt) ;
int  Setupbrowser2callback(int item,int i,void *Tmp) ;
int  Setupbutton4callback(int butno,int i,void *Tmp) ;
void  Setupbutton4init(DIN *B,void *pt) ;
int  Setupbutton5callback(int butno,int i,void *Tmp) ;
void  Setupbutton5init(DIN *B,void *pt) ;
int  Setupsplbutton1callback(int butno,int i,void *Tmp) ;
void  Setupsplbutton1init(DIL *B,void *pt) ;
int Setupinit(void *Tmp) ;
int Setupcleanup(void *Tmp) ;
int ModifySetup(void *Tmp,int GrpId) ;
int SetupCallBack(void *Tmp,void *tmp) ;
int SetupResizeCallBack(void *Tmp) ;
int SetupWaitCallBack(void *Tmp) ;
